external_components:
  - source:
      type: git
      url: https://github.com/ljan/ESPHomeCoffeeAssistant

globals:
  - id: single_grind_time
    type: int
    initial_value: '12000'
  - id: double_grind_time
    type: int
    initial_value: '25000'

custom_component:
  - id: grinder
    lambda: |-
      auto grinder = new GrinderComponent();
      grinder->set_button_pin(5);
      grinder->set_grinder_pin(14);
      grinder->set_max_grind_time(600000);  // 10 minutes
      grinder->set_single_grind_time(id(single_grind_time));  // Pass global variable
      grinder->set_double_grind_time(id(double_grind_time));  // Pass global variable
      return {grinder};

sensor:
  - platform: template
    name: "Single Grind Time"
    id: single_grind_time_sensor
    update_interval: 10s
    lambda: |-
      return id(single_grind_time);
    on_value:
      then:
        - lambda: |-
            id(grinder).set_single_grind_time(x);

  - platform: template
    name: "Double Grind Time"
    id: double_grind_time_sensor
    update_interval: 10s
    lambda: |-
      return id(double_grind_time);
    on_value:
      then:
        - lambda: |-
            id(grinder).set_double_grind_time(x);
